name:                VB6-optim
version:             0.1.0.0
github:              "visual2000/VB6-optim"
license:             BSD3
author:              "Paul"
maintainer:          "paul@inktvis.org"
copyright:           "Copyright (c) 2020 Paul D."

build-type: Custom
custom-setup:
  dependencies:
    - Cabal
    - base
    - uuagc >= 0.9
    - uuagc-cabal >= 0.9

extra-source-files:
- README.md
- ChangeLog.md
- src/AG.ag
- src/AG/Base.ag
- uuagc_options

# Metadata used when publishing your package
synopsis:            Code transformation and optimisation for Visual Basic 6
category:            Language Tools

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/visual2000/VB6-optim#readme>

dependencies:
- array
- base >= 4.7 && < 5
- containers
- ini
- mtl
- pretty
- regex-compat
- text
- uuagc >= 0.9

library:
  source-dirs: src
  # Hpack doesn't know about generated modules, so we have to add a
  # list here.  They get added to `exposed-modules'.
  generated-exposed-modules:
    - AG
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-incomplete-uni-patterns

  # default-extensions for the benefit of AGs, which don't allow
  # language extension specifications
  other-extensions: CPP
  default-extensions:  StandaloneDeriving
  dependencies:
  - array
  - containers
  - mtl

executables:
  VB6-optim-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VB6-optim
    - directory
    - filepath
    - haskeline

tests:
  VB6-optim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VB6-optim
    - hspec
